### ISSUE TITLE
Convert to styled-components for styling

### ISSUE THREAD

**Issue by trevoreyre** [healthwise/healthwise-ui#1]
# core
- [x] Accordion
- [x] AccordionGroup
- [x] AppBar
- [x] BlockHeading
- [x] Button
- [x] ButtonGroup
- [x] Card
- [x] Checkbox
- [x] CssBaseline
- [x] CssParser
- [x] DropDown
- [x] FeatureFlipper
- [x] Footer
- [x] HealthwiseLogo
- [x] Icon
- [x] IconArray
- [x] Image
- [x] InputText
- [x] KeyGen
- [x] LikertScale
- [x] LoadingIndicator
- [x] Message
- [x] Modal
- [x] PrintOnly
- [x] ProgressBar
- [x] Radio
- [x] ReduxUtil
- [x] References
- [x] ScreenReaderOnly
- [x] SvgImage
- [x] Tab
- [x] TabGroup
- [x] Table
- [x] TextArea
- [x] Theme
- [x] Translation
- [x] ValidationError
- [x] VideoThumbnail

# content
- [ ] Action
- [ ] Article
- [ ] CallToAction
- [ ] Credits
- [ ] CreditsAndReferences
- [ ] Insights
- [ ] MediaCredits
- [ ] MediaGallery
- [ ] MediaServiceVideo
- [ ] Slideshow
- [ ] Story
- [ ] Video

**Comment by nathanlogan** [comment]
Since we moved the "remaining" components into [another repo](https://github.com/healthwise/structured-content-ui), I'm closing this as completed.
